### ISSUE TITLE
docker-compose how to enable gui

### ISSUE THREAD

**Issue by kai456789** [aledipa/Free-GPT4-WEB-API#66]
docker-compose how to enable gui 

How to add parameters to yml to activate Thank you!

**Comment by git-malik** [comment]
This is an example of a `docker-compose.yml` file for activating the web interface
``` yml
#docker-compose.yml
services:
  api:
    image: "d0ckmg/free-gpt4-web-api:latest"
    user: www-data
    ports:
      - "5500:5500"
    command: --enable-gui --password YOUR_PASSWORD # --other-parameters
```
